// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaApp.DbAccess;

#nullable disable

namespace NinjaApp.Migrations
{
    [DbContext(typeof(MyNinjaDbContext))]
    [Migration("20241103134928_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("GoldWorth")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 5,
                            GoldWorth = 300,
                            Intelligence = 2,
                            Name = "Diamond Sword",
                            Strength = 10,
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Agility = 3,
                            GoldWorth = 200,
                            Intelligence = 1,
                            Name = "Diamond Helmet",
                            Strength = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Agility = 5,
                            GoldWorth = 300,
                            Intelligence = 2,
                            Name = "Diamond Chestplate",
                            Strength = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Agility = 3,
                            GoldWorth = 200,
                            Intelligence = 1,
                            Name = "Diamond Boots",
                            Strength = 5,
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Agility = 5,
                            GoldWorth = 300,
                            Intelligence = 2,
                            Name = "Lord of the Ring",
                            Strength = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Agility = 3,
                            GoldWorth = 200,
                            Intelligence = 1,
                            Name = "Pearl Necklace",
                            Strength = 5,
                            Type = 5
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfGold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfGold = 100,
                            Name = "Shadow"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfGold = 150,
                            Name = "Blade"
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.NinjaEquipment", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("NinjaId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("NinjaEquipments");

                    b.HasData(
                        new
                        {
                            NinjaId = 1,
                            EquipmentId = 1
                        },
                        new
                        {
                            NinjaId = 2,
                            EquipmentId = 2
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.NinjaEquipment", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany("NinjaEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany("NinjaEquipments")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Navigation("NinjaEquipments");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Navigation("NinjaEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
