// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaApp.DbAccess;

#nullable disable

namespace NinjaApp.Migrations
{
    [DbContext(typeof(MyNinjaDbContext))]
    [Migration("20241103173533_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("GoldWorth")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 5,
                            GoldWorth = 100,
                            Intelligence = 3,
                            Name = "Diamond Sword",
                            Strength = 20,
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Agility = 4,
                            GoldWorth = 35,
                            Intelligence = 2,
                            Name = "Diamond Helmet",
                            Strength = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Agility = 6,
                            GoldWorth = 50,
                            Intelligence = 3,
                            Name = "Diamond Chestplate",
                            Strength = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Agility = 7,
                            GoldWorth = 25,
                            Intelligence = 9,
                            Name = "Diamond Boots",
                            Strength = 4,
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Agility = 5,
                            GoldWorth = 22,
                            Intelligence = 8,
                            Name = "Lord of the Ring",
                            Strength = 6,
                            Type = 4
                        },
                        new
                        {
                            Id = 6,
                            Agility = 3,
                            GoldWorth = 15,
                            Intelligence = 4,
                            Name = "Pearl Necklace",
                            Strength = 7,
                            Type = 5
                        },
                        new
                        {
                            Id = 7,
                            Agility = 6,
                            GoldWorth = 28,
                            Intelligence = 3,
                            Name = "Iron Sword",
                            Strength = 16,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Agility = 4,
                            GoldWorth = 32,
                            Intelligence = 2,
                            Name = "Iron Helmet",
                            Strength = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Agility = 7,
                            GoldWorth = 45,
                            Intelligence = 4,
                            Name = "Iron Chestplate",
                            Strength = 13,
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Agility = 8,
                            GoldWorth = 27,
                            Intelligence = 10,
                            Name = "Iron Boots",
                            Strength = 5,
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            Agility = 9,
                            GoldWorth = 18,
                            Intelligence = 5,
                            Name = "Speed Ring",
                            Strength = 4,
                            Type = 4
                        },
                        new
                        {
                            Id = 12,
                            Agility = 4,
                            GoldWorth = 12,
                            Intelligence = 3,
                            Name = "Diamond Necklace",
                            Strength = 6,
                            Type = 5
                        },
                        new
                        {
                            Id = 13,
                            Agility = 6,
                            GoldWorth = 14,
                            Intelligence = 2,
                            Name = "Wooden Sword",
                            Strength = 14,
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Agility = 4,
                            GoldWorth = 26,
                            Intelligence = 2,
                            Name = "Wooden Helmet",
                            Strength = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Agility = 6,
                            GoldWorth = 42,
                            Intelligence = 3,
                            Name = "Wooden Chestplate",
                            Strength = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Agility = 8,
                            GoldWorth = 24,
                            Intelligence = 7,
                            Name = "Wooden Boots",
                            Strength = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = 17,
                            Agility = 5,
                            GoldWorth = 17,
                            Intelligence = 6,
                            Name = "Strength Ring",
                            Strength = 10,
                            Type = 4
                        },
                        new
                        {
                            Id = 18,
                            Agility = 10,
                            GoldWorth = 11,
                            Intelligence = 2,
                            Name = "Agility Necklace",
                            Strength = 5,
                            Type = 5
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountOfGold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Ninjas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfGold = 100,
                            Name = "Shadow"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfGold = 150,
                            Name = "Blade"
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.NinjaEquipment", b =>
                {
                    b.Property<int>("NinjaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("NinjaId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("NinjaEquipments");

                    b.HasData(
                        new
                        {
                            NinjaId = 1,
                            EquipmentId = 1
                        },
                        new
                        {
                            NinjaId = 2,
                            EquipmentId = 2
                        });
                });

            modelBuilder.Entity("NinjaApp.Models.NinjaEquipment", b =>
                {
                    b.HasOne("NinjaApp.Models.Equipment", "Equipment")
                        .WithMany("NinjaEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NinjaApp.Models.Ninja", "Ninja")
                        .WithMany("NinjaEquipments")
                        .HasForeignKey("NinjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjaApp.Models.Equipment", b =>
                {
                    b.Navigation("NinjaEquipments");
                });

            modelBuilder.Entity("NinjaApp.Models.Ninja", b =>
                {
                    b.Navigation("NinjaEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
